/// librollenspielsache is a library for managing tabletop RPG gameplay.
/// It is designed to help automate some of the busywork behind game mastering so one can focus on the game itself.
/// This library exposes an API for manipulating and serializing various game objects
mod character;
mod dice;
mod error;
mod game_system;
mod modifier;
mod redis;
mod skill;

pub use dice::*;

use libc::c_char;
use std::ffi::CString;

/// Helper function to free strings generated by Rust
/// Clients need to call this to ensure proper cleanup
#[no_mangle]
pub unsafe extern "C" fn string_free(s: *mut c_char) {
    {
        if s.is_null() {
            // nothing to do
            return;
        }
        // Otherwise, trigger the Rust destructor when it goes out of scope
        CString::from_raw(s)
    };
}

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
